In [1]:
import numpy as np
import random

In [2]:
class TreeNode:
    def __init__(self, val=0, left=None, right=None):
        self.val = val
        self.left = left
        self.right = right

head = TreeNode(0,left=TreeNode(5,left=TreeNode(3),right=TreeNode(4)),right=TreeNode(15,left=TreeNode(12),right=TreeNode(8)))


In [3]:
result = []
def traversal(root):
    if root == None:
        return

    traversal(root.left)
    result.append(root.val)
    traversal(root.right)
traversal(head)

result

[3, 5, 4, 0, 12, 15, 8]

In [4]:
def generate_problem(n):
    return [random.randint(0,100) for _ in range(n)]

x = [54,49,2]
print(x)
y = generate_problem(10)
y

[54, 49, 2]


[88, 100, 82, 75, 89, 11, 83, 20, 23, 46]

In [5]:
def subset(arr,idx, path):
    res.append(path)
    print(path)
    for i in range(idx, len(arr)):
        if i > idx and arr[i] == arr[i-1]:
            continue
        subset(arr,i+1, path+[arr[i]])
        
res = []
subset(x,0,[])


print()

res = []
subset(y,0,[])


[]
[54]
[54, 49]
[54, 49, 2]
[54, 2]
[49]
[49, 2]
[2]

[]
[88]
[88, 100]
[88, 100, 82]
[88, 100, 82, 75]
[88, 100, 82, 75, 89]
[88, 100, 82, 75, 89, 11]
[88, 100, 82, 75, 89, 11, 83]
[88, 100, 82, 75, 89, 11, 83, 20]
[88, 100, 82, 75, 89, 11, 83, 20, 23]
[88, 100, 82, 75, 89, 11, 83, 20, 23, 46]
[88, 100, 82, 75, 89, 11, 83, 20, 46]
[88, 100, 82, 75, 89, 11, 83, 23]
[88, 100, 82, 75, 89, 11, 83, 23, 46]
[88, 100, 82, 75, 89, 11, 83, 46]
[88, 100, 82, 75, 89, 11, 20]
[88, 100, 82, 75, 89, 11, 20, 23]
[88, 100, 82, 75, 89, 11, 20, 23, 46]
[88, 100, 82, 75, 89, 11, 20, 46]
[88, 100, 82, 75, 89, 11, 23]
[88, 100, 82, 75, 89, 11, 23, 46]
[88, 100, 82, 75, 89, 11, 46]
[88, 100, 82, 75, 89, 83]
[88, 100, 82, 75, 89, 83, 20]
[88, 100, 82, 75, 89, 83, 20, 23]
[88, 100, 82, 75, 89, 83, 20, 23, 46]
[88, 100, 82, 75, 89, 83, 20, 46]
[88, 100, 82, 75, 89, 83, 23]
[88, 100, 82, 75, 89, 83, 23, 46]
[88, 100, 82, 75, 89, 83, 46]
[88, 100, 82, 75, 89, 20]
[88, 100, 82, 75, 89, 20, 23]
[88, 100, 82, 75,

In [8]:
def generate_problem(n):
    return [random.randint(1,100) for _ in range(n)],random.randint(0,100)

x = ([85,90,76,2,86],64)
print(x)
y = generate_problem(10)
y

([85, 90, 76, 2, 86], 64)


([9, 79, 36, 48, 23, 31, 1, 43, 67, 36], 20)

In [9]:

def combination_sum(arr, target):
    ans,temp = [],[]
    arr = sorted(list(set(arr)))
    findNumbers(ans, arr, temp, target, 0)
    return ans
 
def findNumbers(ans, arr, temp, target, index):
    if(target == 0):
        ans.append(list(temp))
        return
    for i in range(index, len(arr)):
        if(target - arr[i]) >= 0:
            temp.append(arr[i])
            findNumbers(ans, arr, temp, target-arr[i], i)
            temp.remove(arr[i])
            
print(combination_sum(x[0],x[1]))
print(combination_sum(y[0],y[1]))

[[2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2]]
[[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 9], [1, 1, 9, 9]]


In [10]:
g = {0: [1, 3, 4], 1: [5], 2: [], 3: [], 4: [], 5: [7], 6: [], 7: []}
print(g)
visited = [False]*len(g)
stack = []
def topsort(v,visited,stack):
    visited[v] = True
    for i in g[v]:
        if visited[i] == False:
            topsort(i,visited,stack)
    stack.insert(0,v)

for i in range(len(g)):
    if visited[i] == False:
        topsort(i,visited,stack)
stack

{0: [1, 3, 4], 1: [5], 2: [], 3: [], 4: [], 5: [7], 6: [], 7: []}


[6, 2, 0, 4, 3, 1, 5, 7]

In [11]:
def generate_problem(n):
    board = [[0]*n for i in range(n)]
    board[n-1][n-1] = -1
    return board
board = generate_problem(8)
print(np.matrix(board))

[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0 -1]]


In [12]:
def cover(board, lab=1, top=0, left=0,side=None):
    if not side: side = len(board)
    s = side // 2
    offsets = (0, -1), (side-1, 0)
    for dy_outer, dy_inner in offsets:
        for dx_outer, dx_inner in offsets:
             if not board[top+dy_outer][left+dx_outer]:
                    board[top+s+dy_inner][left+s+dx_inner] = lab
    lab += 1
    if s > 1:
        for dy in [0, s]:
            for dx in [0, s]:
                lab = cover(board, lab, top+dy, left+dx, s)
    return lab 

In [13]:
cover(board)
print(np.matrix(board))

[[ 3  3  4  4  8  8  9  9]
 [ 3  2  2  4  8  7  7  9]
 [ 5  2  6  6 10 10  7 11]
 [ 5  5  6  1  1 10 11 11]
 [13 13 14  1 18 18 19 19]
 [13 12 14 14 18 17 17 19]
 [15 12 12 16 20 17 21 21]
 [15 15 16 16 20 20 21 -1]]
